### ISSUE TITLE
Contracts with same symbol but different multipliers cannot be specified

### ISSUE THREAD

**Issue by miguelvm** [ranaroussi/qtpylib#11]
There are contracts like DAX futures which are specified in Interactive Brokers with the same symbol but are in fact two different contracts: DAX with multiplier 25 and DAX (mini-DAX) with multiplier 5. The symbols.csv should have a field for the multiplier of the contract.

**Comment by ranaroussi** [comment]
The mini-Dax Futures symbol is FDXM, not DAX.

Tuple should be something like:
("FDXM", "FUT", "DTB", "EUR", EXPIRY, "")

See here for complete contract spec on IB:
https://misc.interactivebrokers.com/cstools/contract_info/v3.9/index.php?action=Details&site=GEN&conid=248032234

**Comment by miguelvm** [comment]
You are right, using FDAX and FDXM works. Thanks Ran.
