### ISSUE TITLE
Support for paper accounts

### ISSUE THREAD

**Issue by pavel-dsg** [ranaroussi/qtpylib#116]

**Comment by pavel-dsg** [comment]
Hi Ran,
Are you planning to add support for paper accounts?
We are not ready yet to subscribe to an actual account and want to test our trading code with a paper account.

While trying to work with it, I get the following error from the blotter:

`qtpylib.blotter: [IB #354] Requested market data is not subscribed.Delayed market data is available.Error&NYMEX/FUT/Top&NYMEX/FUT/Top`

**Comment by ranaroussi** [comment]
Hi Pavel,

You still need market data subscription to test your strategies using a paper trading account. You can use QTPyLib as a backtester without market data subscription if you have the data as csv.
