### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Admiralhunter** [ranaroussi/qtpylib#124]
**Describe the bug**
When running the blotter.py that is shown in the documentation I get an error for a command. I believe this error prevents my script from downloading the data into the symbols.csv

**To Reproduce**
Write the blotter.py file from the documentation. The command "pgrep" is not valid is the output in the python output.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10

**Additional context**
Looking online it seems the pgrep is a linux only command. I was wondering if there's a work around for that section of code.

**Comment by Admiralhunter** [comment]
Nevermind I seem to not get this error when I put the IB gateway in simulation mode.

**Comment by XBKZ** [comment]
I have the same problem on Windows  10. I think the command pgrep don't exist in Windows. 
Know somebody  how to fix that ? It's in blotter.py 👍
def _blotter_file_running():
        try:
            # not sure how this works on windows...
            command = 'pgrep -f ' + sys.argv[0]
With what can we replace pgrep -f  (to search in the processes names) ???
Or need I definitively make run QtPyLib in a Linux environment ?
Thank you for your help
