### ISSUE TITLE
multiple instruments

### ISSUE THREAD

**Issue by jonahern** [ranaroussi/qtpylib#128]
back testing (example strategies) with multiple instruments results in error:

> \qtpylib\algo.py", line 881, in _update_window
>     df = tools.resample(df, resolution=resolution, tz=tz)
>   File "C:\Users\ahern\Miniconda3\lib\site-packages\qtpylib\tools.py", line 695, in resample
>     ['_idx_']].min().max().values[-1]).replace('T', ' ')
> IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by IlyaKrotov** [comment]
I've got the same thing and I cannot fix it.
