### ISSUE TITLE
--start --end

### ISSUE THREAD

**Issue by jonahern** [ranaroussi/qtpylib#132]
from documentation:

> --start Backtest start date (YYYY-MM-DD [HH:MM:SS[.MS])
> --end Backtest end date (YYYY-MM-DD [HH:MM:SS[.MS])

what is the correct method to set the start and stop time for the back test.

> --start 20190726 09:30:00 --end 20190726 09:45:00

for example seems to have no effect on selecting the times

**Comment by jonahern** [comment]
seems like this works:
> --start 2019-07-26-09:30:00 --end 2019-07-26-09:45:00

**Comment by jonahern** [comment]
> --start 2019-07-26-09:31:00 
works, but 
> --end 2019-07-26-09:45:00
doesn't?

**Comment by kalpesh-99** [comment]
Hi, I'm running into the same issue here. @jonahern how did you resolve it?
