### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by dwhe123** [ranaroussi/qtpylib#147]
I am running python 3.6 in ubuntu and I am new to python so please be nice.

basically I want to buy when the 5 day moving average crosses the 10 day moving average AND the 10 day is above the 20 day.

        dataframe.loc[
            (
                (dataframe['sma5'] qtpylib.crossed_above (dataframe['sma10'])) &
                (dataframe['sma10'] > dataframe['sma20'])

            )
            'buy'] = 1

        return dataframe

#I know that my code is written wrong and my syntax is wrong so that is why I need help. 

#Similarly, for the close I would like to close once price breaks below the 5 day moving average:
        dataframe.loc[
            (

                    (dataframe['close'] crossed_below (dataframe['sma5']))
            ),
            'sell'] = 1
        return dataframe

**Comment by dwhe123** [comment]
im all alone... :'(

**Comment by jonahern** [comment]
only die hard fanatics are trying to code trading algos on Christmas!  If I got anything to work it was the MA example...are you not able to get that to work?

**Comment by dwhe123** [comment]
I got this figured out but through no help of this forum :(

**Comment by jonahern** [comment]
Ya, there's not much activity on here
