### ISSUE TITLE
[BUG] pip install error (different than issue #141)

### ISSUE THREAD

**Issue by jus-tinian** [ranaroussi/qtpylib#163]
**Describe the bug**

```
ERROR: Command errored out with exit status 1:
command: /opt/anaconda3/envs/TrendFollowing/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = 
'"'"'/private/var/folders/d2/cmtjghmx1pq2y4mpyw8387rr0000gn/T/pip-install-xqol4hiv/qtpylib/setup.py'"'"'; 
__file__='"'"'/private/var/folders/d2/cmtjghmx1pq2y4mpyw8387rr0000gn/T/pip-install-xqol4hiv/qtpylib/setup.py'"'"';
f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, 
__file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/d2/cmtjghmx1pq2y4mpyw8387rr0000gn/T/pip-pip-egg-
info-o7m_h1lf
cwd: /private/var/folders/d2/cmtjghmx1pq2y4mpyw8387rr0000gn/T/pip-install-xqol4hiv/qtpylib/
Complete output (1 lines): error in QTPyLib setup command: "values of 'package_data' dict" must be a list of strings (got 
'qtpylib/_webapp/*')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**To Reproduce**
Attempted to install using 3 methods: in PyCharm project Python Interpreter (Conda env); using pip installation line from docs in PyCharm terminal, and in iTerm with same pip install

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.7

**Comment by qtbgo** [comment]
have you solved your problem?

**Comment by qtbgo** [comment]
> **Describe the bug**
> 
> ```
> ERROR: Command errored out with exit status 1:
> command: /opt/anaconda3/envs/TrendFollowing/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = 
> '"'"'/private/var/folders/d2/cmtjghmx1pq2y4mpyw8387rr0000gn/T/pip-install-xqol4hiv/qtpylib/setup.py'"'"'; 
> __file__='"'"'/private/var/folders/d2/cmtjghmx1pq2y4mpyw8387rr0000gn/T/pip-install-xqol4hiv/qtpylib/setup.py'"'"';
> f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, 
> __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/d2/cmtjghmx1pq2y4mpyw8387rr0000gn/T/pip-pip-egg-
> info-o7m_h1lf
> cwd: /private/var/folders/d2/cmtjghmx1pq2y4mpyw8387rr0000gn/T/pip-install-xqol4hiv/qtpylib/
> Complete output (1 lines): error in QTPyLib setup command: "values of 'package_data' dict" must be a list of strings (got 
> 'qtpylib/_webapp/*')
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ```
> 
> **To Reproduce**
> Attempted to install using 3 methods: in PyCharm project Python Interpreter (Conda env); using pip installation line from docs in PyCharm terminal, and in iTerm with same pip install
> 
> **Desktop (please complete the following information):**
> 
> * OS: macOS
> * Version 10.15.7

have you solved your problem?
