### ISSUE TITLE
backfill

### ISSUE THREAD

**Issue by JfourierX** [ranaroussi/qtpylib#2]
Any plans handle disconnects and/or automatic backfill of history ?

**Comment by ranaroussi** [comment]
This is actually a nice idea. I'll try to implement this functionality in one of the next releases.

**Comment by ranaroussi** [comment]
Feature addd in version 1.5.45

See the [changelog](https://github.com/ranaroussi/qtpylib/blob/master/CHANGELOG.rst) for complete info and caveats
