### ISSUE TITLE
slow backtest

### ISSUE THREAD

**Issue by post2web** [ranaroussi/qtpylib#21]
On my backtest with 1min bars strateg.on_bar receives a bar per 2.5 seconds. Is this a normal behavior?

**Comment by ranaroussi** [comment]
Nope. That was supposed to be a 0.25s delay between bars and I mistakenly wrote it as 2.5s. 
Fixed in version 1.5.25 (released now).

Please upgrade:

```
$ pip install qtpylib --upgrade --no-cache-dir
```

Enjoy!
