### ISSUE TITLE
Algo with 1S resolution does not get a bar every second

### ISSUE THREAD

**Issue by jkleint** [ranaroussi/qtpylib#23]
If I request a bar every second, I would expect to get, well... a bar every second, even if the quote has not changed.

```
from qtpylib.algo import Algo
from time import time


class SecBar(Algo):
    def on_bar(self, instrument):
        print('bar {:.0f} {}'.format(time(), instrument.bar['datetime']))


if __name__ == '__main__':
    SecBar(["AAPL"], '1S').run()
```

But as you can see there are multi-second gaps between bars:

```
$ python sec_test.py 
bar 1478844262 2016-11-11 06:04:21
bar 1478844264 2016-11-11 06:04:23
bar 1478844267 2016-11-11 06:04:26
bar 1478844269 2016-11-11 06:04:28
bar 1478844272 2016-11-11 06:04:32
bar 1478844274 2016-11-11 06:04:34
bar 1478844277 2016-11-11 06:04:37
bar 1478844280 2016-11-11 06:04:40
```

Am I misunderstanding how bars are supposed to work?

**Comment by ranaroussi** [comment]
Well, it should in theory, but I took a different approach here in favor of efficiency...

The way this works now is that it resamples data to the strategy resolution on every new tick that is received, so if there's a 5 second gap between ticks, you won't get bar events during that time. 

However, when the new tick is received the `self.bars` / `instrument.bars` / `instrument.get_bars()` should get you the full bar history for every second - even if the quote has not changed.

The idea behind this decision was that if nothing's happening in the market, its likely that the strategy shouldn't take any action - but when something is happening (a tick received), you'll have access to the full data for calculating moving averages, etc.

I'm still thinking if there's an elegant way (or a reason) to have the bar event fire every second that doesn't involves without using threads and without putting unnecessary strain on the system.

**Comment by ranaroussi** [comment]
Ok... couldn't help it :)

If you'll add `"force_resolution" = True` to your strategy initializer, you'll get a bar every `resolution` - regardless of whether or not new ticks were received.

Version 1.5.27 released.

**Comment by jkleint** [comment]
Unfortunately it's still skipping beats with `force_resolution=True`.  I'll see if I can fix it.

```
$ python sec_test.py 
bar 1478895960 2016-11-11 20:26:00
bar 1478895961 2016-11-11 20:26:01
bar 1478895962 2016-11-11 20:26:02
bar 1478895964 2016-11-11 20:26:04
bar 1478895965 2016-11-11 20:26:05
bar 1478895966 2016-11-11 20:26:06
bar 1478895967 2016-11-11 20:26:07
bar 1478895969 2016-11-11 20:26:09
bar 1478895970 2016-11-11 20:26:10
bar 1478895971 2016-11-11 20:26:11
bar 1478895973 2016-11-11 20:26:13
bar 1478895975 2016-11-11 20:26:15
bar 1478895976 2016-11-11 20:26:16
```

**Comment by jkleint** [comment]
So I tracked the issue down to `Algo._tick_handler()`; it's not a thread/timing issue, it's how `_tick_handler` decides if it's got a new bar:

```
    if len(bar.index) > self.tick_bar_count > 0:
        self._bar_handler(bar)
```

Which I think is saying if this bar has more bars than the last bar, call the bar handler?  I don't really understand this section, but `len(bar.index)` and `self.tick_bar_count` are often the same, so it doesn't fire a bar.

**Comment by ranaroussi** [comment]
Hopefully fixed in v. 1.5.29

**Comment by jkleint** [comment]
Thanks, much better.  It still skips seconds after running for a while, but I can probably live with it.

**Comment by rastegar527** [comment]
I see the same issue. It skips seconds after running for a while.
