### ISSUE TITLE
hangs when backtesting

### ISSUE THREAD

**Issue by post2web** [ranaroussi/qtpylib#24]
Just installed qtpylib-1.5.27, a botter running. The strategy looks like this:
<pre>
class Strategy(Algo):
    def on_bar(self, instrument):
        print('.')
strategy = Strategy(
    instruments=["GOOG"],
    resolution="1min",
    backtest=True,
    start='2016-01-05',
    end='2016-01-05',
    output='portfolio.pkl'
)
print(strategy.backtest) # prints True
strategy.run()
</pre>
It hangs with CPU usage of 100% and nothing is printed.
One minute bars are in the database. Mysql only shows two sleeping connections from the botter.
When I stop the strategy script ( botter still running  ) the cpu usage goes back to normal.

**Comment by ranaroussi** [comment]
I'm not sure why is that. I ran your code on my MacBook and trading server and it worked just fine (the second level resolution backtest had a bug that was fixed in latest commit (a97e20b).

http://screencast.com/t/nefkHQ78WsP

Are you connecting to a remote MySQL server by any chance?

**Comment by post2web** [comment]
I am connecting to a local mysql inside a docker container. It connects with TCP, not socket. I can see new connections to the mysql server when the botter starts.

**Comment by ranaroussi** [comment]
@jkleint - any idea what may be causing this? This works without a hitch on my local machine and trading server...

**Comment by jkleint** [comment]
It also works for me.  @post2web when you Ctrl-C it, it should give you a stack trace; if you could paste in the trace, maybe from a few kills, it might help.  You could also turn up the logging in blotter.py to DEBUG.

**Comment by ranaroussi** [comment]
Implemented @jkleint suggestion in version 1.5.39, but kept a 0.1s delay in order to be nice to the CPU and allow catching `Ctrl+c`.

Closing this issue. Please re-open if problem persists.

**Comment by jonahern** [comment]
is this the same issue?  furthest point achieved in a backtest is freezing on "Backfilling Historical..."
![ScreenClip](https://user-images.githubusercontent.com/39503673/62000913-657e8080-b0b1-11e9-9af1-486c036a0e71.png)
