### ISSUE TITLE
Instrument CASH

### ISSUE THREAD

**Issue by ErnstTmp** [ranaroussi/qtpylib#3]
Hi Ran,
your qtpylib is great. I would like to treat CASH instruments (EUR,CASH,IDEALPRO,USD,,, in symbols.csv), and it looks like the incomming quote data is not treated, and neither stored in the DB and not otherwise.
The incomming quote looks like
QUOTE is  {'bid': 1.1136999999999999, 'lastsize': 0.0, 'asksize': 18000000.0, 'ask': 1.11375, 'last': 0.0, 'bidsize': 3178000.0}

It is broadcasted, but not stored in the DB with log2db, and not stored internally.

Can you give me a hint how to integrate this?

Thanks and kind regards,
Ernst

**Comment by homeyi** [comment]
i  met same problem.

**Comment by ranaroussi** [comment]
Hey,

QTPyLib doesn't currently store quotes in MySQL (only ticks and 1min bars are stored). 

The problem comes from the fact that IB doesn't send `RTVOLUME` for cash markets, so there's no "tick" to store. I've fixed that in version 1.4.8 by creating a "synthetic tick" from quote data.

Please upgrade to the latest version 1.4.8 and things should be working ok.

```
$ pip install qtpylib --upgrade --no-cache-dir
```

LMK if that worked,
Ran

**Comment by ErnstTmp** [comment]
Hi Ran,

thank you very much for the fast fix, this is excellent! I will try it 
ASAP and tell you how it works.

Kind regards and have a nice weekend,

Ernst

**Comment by ErnstTmp** [comment]
Ran,

it is too late today, I do not get any quotes from IB - I will try 
Sunday night. But it looks good, entries in the symbol table are correct.

Kind regards

Ernst

**Comment by ranaroussi** [comment]
Glad to hear it. Please let me know if everything's working as it should once the markets have opened again. Enjoy the weekend!

**Comment by homeyi** [comment]
Ran , i upgraded pyqtlib,now CASH instruments can get tick and run ok,thank for you fixed it.

**Comment by ErnstTmp** [comment]
Hi Ran,

thank you very much for implementing this so fast, it works very well, I 
tested it over night.

Kind regards

Ernst
