### ISSUE TITLE
1T vs 1S

### ISSUE THREAD

**Issue by rastegar527** [ranaroussi/qtpylib#34]
I ran this strategy. When I set resolution to '1K' I get the bars, however when I set it to '1T' I don't get any bar even if wait many minutes:

```python
class TestStrategy(Algo):
    def on_start(self):
         pass

    def on_bar(self, instrument):
        # nothing exiting here...
        bar = instrument.get_bar()
        print("BAR:", bar)
 
if __name__ == "__main__":
    # get most active ES contract to trade
]        instruments = [ "AAPL" ],
        resolution  = "1T" # 1Min bar resolution (Pandas "resample" resolutions)
    )
    strategy.run()
```

**Comment by ranaroussi** [comment]
There's no strategy initialization in your code, and there's also a `]` at the beginning on the `instrument=...` line. Does it also exist on the code you're running? 

Please try running this code and let me know:

```python
class TestStrategy(Algo):
    def on_start(self):
         pass

    def on_tick(self, instrument):
        print(".", end="")

    def on_bar(self, instrument):
        bar = instrument.get_bar()
        print("\n ==> BAR:", bar)
 
if __name__ == "__main__":
    strategy = TestStrategy(
        instruments = [ "AAPL" ],
        resolution  = "1T" # 1Min bar resolution (Pandas "resample" resolutions)
    )
    strategy.run()
```

**Comment by rastegar527** [comment]
Hi Ran. I ran the example you gave.

**python print_data.py 
Server Version: 76
TWS Time at connection:20161202 16:42:58 CST
^C.......................................................................................................................................................................................................................................................................................................................................**

No output. The blotter is working. If I change the 1T to 1K, it works fine.

**Comment by ranaroussi** [comment]
When printing with the `end=""` parameter, you should add `flush=True` to have it actually printing... :)

This should work:

```python
from qtpylib.algo import Algo

class TestStrategy(Algo):
    def on_start(self):
         pass

    def on_tick(self, instrument):
        print(".", end="", flush=True)

    def on_bar(self, instrument):
         print(">", end="", flush=True)

if __name__ == "__main__":
    strategy = TestStrategy(instruments = [ "AAPL" ], resolution = "1K")
    strategy.run()
```
