### ISSUE TITLE
Many symbols

### ISSUE THREAD

**Issue by rastegar527** [ranaroussi/qtpylib#35]
I'd like to implement a day trading strategy in following manner: each day, before the market starts, I need to calculate a list of signals for all S&P500 and perform an screening process and choose about 100 companies. Then I need to trade them on a minute based data.  Given the high number of companies that I would like to track in the market on minute basis, are you aware of any limitation in the framework to handle that volume of symbols?

This is related issue to [issue with multi-instrument #37]
Thanks again Ran!

**Comment by ranaroussi** [comment]
The bugs reported in issues #36 and #37 have been fixed with version `1.5.41`.

Please upgrade and confirm everything's working as it should now.

To upgrade, run:

```bash
$ pip install qtpylib --upgrade --no-cache-dir
```

Thanks
