### ISSUE TITLE
symbols

### ISSUE THREAD

**Issue by JfourierX** [ranaroussi/qtpylib#4]
It would be nice to include the contract tuple values in symbols table and provide apis to query symbolid for specified contract tuple and internal single word symbol.

**Comment by ranaroussi** [comment]
While QTPyLib doesn't have this functionality, it does offer a few methods that can streamline the process of obtaining the relevant tuple for the instruments you want to trade.

Obviously, US stocks doesn't need any shortcut or api... simply use `AAPL`, `MSFT`, etc...

For any of CME Group's Futures (inc. CME, GLOBEX, CBOT, NYMEX and COMEX) you can use either the [`futures.get_active_contract(...)`](http://qtpylib.io/docs/latest/futures.html#most-traded-contract-expiration) or [`FUT.CL`](http://qtpylib.io/docs/latest/futures.html#most-traded-contract-expiration) methods - which will automatically trade **most active futures contract month**, based on the previous day’s volume and open interest.

You can also get contract details for any Futures contract traded on IB using `futures.get_ib_futures(...)` which will give you this data:

```
{
  'class': 'CL',
  'currency': 'USD',
  'description': 'Light Sweet Crude Oil',
  'exchange': 'NYMEX',
  'has_options': True,
  'intraday_initial': 2175.0,
  'intraday_maintenance': 1740.0,
  'overnight_initial': 4350.0,
  'overnight_maintenance': 3480.0,
  'symbol': 'CL'
}
```

You can then construct your 
```
from qtpylib import futures

contract = futures.get_ib_futures("CL")
tuple = (contract['symbol'], "FUT", contract['exchange'], contract['currency'], 201612, 0.0, "")
```

Hope that helps :)

**Comment by ranaroussi** [comment]
This functionality was just added to version 1.4.9 via the `futures.make_tuple(...)` method.

Simply pass the symbol, expiry (and optionally, exchange) and you're good :)

```
from qtpylib import futures

strategy = MyStrategy(
    instruments = [
        futures.make_tuple("CL", 201612),
        futures.make_tuple("GBL", 201612, exchange="DTB")
    ],
    ...
)
```

More info can be found in the docs:
http://qtpylib.io/docs/latest/futures.html#auto-tuple-generation

Enjoy!

**Comment by ranaroussi** [comment]
Marking this issue as closed for now
