### ISSUE TITLE
Question with backtesting

### ISSUE THREAD

**Issue by rastegar527** [ranaroussi/qtpylib#42]
Can we connect the blotter to historical data that are obtained from vendors such https://quantquote.com/?

What are the options for backtesting. The documentation doesn't cover it much.

Thanks team!

**Comment by ranaroussi** [comment]
Currently there's to way upload backtesting data, but I'm working on a solution for this. 

I've just introduced automatic backfilling of missing historical data in the `develop` branch, as suggested in issue #2.  I'll run some more tests in the next couple of days and if everything checks out, I'll push it to the `master` branch.

**Comment by rastegar527** [comment]
Thanks Ran. May I ask how would you currently backtest your strategies?

**Comment by ranaroussi** [comment]
I have a hacked version of QTPyLib that allows me to import CSV files in run time, tho it is buggy :) Once I get it working without bugs, I'll release it. It should be as strait forward as adding `--data path/to/file.csv` when running your strategy file. Stay tuned 👍

**Comment by rastegar527** [comment]
That's great! Are you planning to implement it such that adding multiple files, one for each stock that is going to be used in the strategy,  would be possible?

Thanks Ran!

**Comment by ranaroussi** [comment]
Latest version support backtesting off of CSV files!

Please see this Notebook for more info:
https://github.com/ranaroussi/qtpylib/blob/master/examples/qtpylib-workflow-example.ipynb

Enjoy :)

**Comment by rastegar527** [comment]
Awesome Ran. I'll start using it and let your if I have any question. Stay warm!
