### ISSUE TITLE
Bracket Order

### ISSUE THREAD

**Issue by rastegar527** [ranaroussi/qtpylib#43]
Does the instrument support bracket order? I cannot find it in the documentation.

**Comment by ranaroussi** [comment]
Sure! You can use a bracket order like so:

```python
instrument.order(
    direction     = "BUY",
    quantity      = 1,
    price         = 100,  # set the price for LMT orders, ommit or set to 0 for MKT orders
    target        = 120,  # brakcet target
    initial_stop  = 90,   # bracket hard stop
    stop_limit    = False # LMT STP / STP stop order
)
```

There are many other parameters you can pass to the `order()` that you should check out here:
http://qtpylib.io/docs/latest/api.html#instrument-api

BTW - if you want to use a bracket order with a trailing stop, use:

```python
instrument.order(
    direction     = "BUY",
    quantity      = 1,
    price         = 100,   # set the price for LMT orders, ommit or set to 0 for MKT orders
    target        = 120,   # brakcet target
    initial_stop  = 90,    # bracket hard stop
    stop_limit    = False, # LMT STP / STP stop order
    trail_stop_at = 110,   # start trailing when price reaches this level
    trail_stop_by = 5,     # % of trailing stop distance from current price
)
```

Or, if you want to control the stoploss manually, use:

```python
instrument.move_stoploss(110) # 110 is the new stop loss now
```

You can also use a shorthand for a buy MKT order (and ommit the `directin` and `price` parametrs)

```python
instrument.buy(quantity=1, ... )
```

...or a buy LMT order

```python
instrument.buy_limit(quantity=1, price=100, ... )
```

Same goes for `instrument.sell` and `instrument.sell_limit` :)

I really recommend familiarizing yourself with the [Instrument API](http://qtpylib.io/docs/latest/api.html#instrument-api), as there are some powerful/helpful stuff :)

One example, you can get the maximum number of Futures contracts you're allowed to to trade, based on your margin, buy calling:

```python
# for overnight holding
max_allowed = instrument.get_max_contracts_allowed(overnight=True)

# for intraday holding
max_allowed = instrument.get_max_contracts_allowed(overnight=False)
```

Live long and prosper, my friend :)
Ran

**Comment by rastegar527** [comment]
Awesome! Thanks Ran for all your help. I'm hoping as I get more comfortable with the package I can start helping with this awesome package. Cheers!

**Comment by ranaroussi** [comment]
I should point out, that complex order types (brackets, trading stops, etc) are not supported when backtesting as this is a feature manages on the Broker side. When backtesting, you should monitor your position and exit your position manually for stops and targets until I add this functionality in backtesting mode.
