### ISSUE TITLE
algo.py UnboundLocalError: local variable 'history' referenced before assignment

### ISSUE THREAD

**Issue by distagon** [ranaroussi/qtpylib#44]
version:
QTPyLib (1.5.45)
ezIBpy (1.12.42)

algo.py line 283, self.bars = history

```python
# get history
if not self.blotter_args["dbskip"] and (self.backtest or self.preload):

    start = self.backtest_start if self.backtest else tools.backdate(self.preload)
    end = self.backtest_end if self.backtest else None

    history = self.blotter.history(
        symbols    = self.symbols,
        start      = start,
        end        = end,
        resolution = self.resolution,
        tz         = self.timezone,
        continuous = self.continuous
    )

    # history needs backfilling?
    if not self.blotter.backfilled:
        # "loan" Blotter our ibConn
        self.blotter.ibConn = self.ibConn

        # call the back fill
        self.blotter.backfill(data=history, resolution=self.resolution, start=start, end=end)

        # re-get history from db
        history = self.blotter.history(
            symbols    = self.symbols,
            start      = start,
            end        = end,
            resolution = self.resolution,
            tz         = self.timezone,
            continuous = self.continuous
        )

        # take our ibConn back :)
        self.blotter.ibConn = None

if self.backtest:
    # initiate strategy
    self.on_start()

    # drip history
    self.blotter.drip(history,
        self._tick_handler if self.resolution[-1] in ("K", "V") else self._bar_handler)

else:
    # place history self.bars
    self.bars = history

    # add instruments to blotter in case they do not exist
    self.blotter.register(self.instruments)

    # initiate strategy
    self.on_start()

    # listen for RT data
    self.blotter.stream(
        symbols       = self.symbols,
        tz            = self.timezone,
        quote_handler = self._quote_handler,
        tick_handler  = self._tick_handler,
        bar_handler   = self._bar_handler,
        book_handler  = self._book_handler
    )
```

**Comment by distagon** [comment]
And why I get into else block?
python strategy_1.py --blotter MainBlotter --log strategy_log

**Comment by ranaroussi** [comment]
Are you back-testing? Please post your strategy initialize parameters

**Comment by distagon** [comment]
here is my trial strategy:
# strategy.py
from qtpylib.algo import Algo
from qtpylib import futures

class DumbAlgo(Algo):

    def on_start(self):
        # optional method that gets called once upon start
        pass

    def on_fill(self, instrument, order):
        # optional method that gets called on every order fill
        pass

    def on_orderbook(self, instrument):
        # optional method that gets called on every orderbook change
        pass

    def on_quote(self, instrument):
        # optional method that gets called on every quote change
        pass

    def on_tick(self, instrument):
        # optional method that gets called on every tick received
        print(".", end="", flush=True)

    def on_bar(self, instrument):
        # optional method that gets called on every bar received
        bars = instrument.get_bars(lookback=168)

        print("--- BARS ------------")
        print(bars)
        print("----------------------")

        last_bar = bars[-1:]
        print("Got Bar ",type(last_bar))
        print("Got Bar ",last_bar)

        dt = last_bar.index[-1]
        unixdate = dt.timestamp()

        print("Datetime ", dt)
        print("Unixdate ", unixdate)



if __name__ == "__main__":

    # initialize the algo
    strategy = DumbAlgo(
        instruments = [
                ("AUD","FUT","GLOBEX","USD",futures.get_active_contract("AUD"),0.0, ""),
                ("BZ","FUT","NYMEX","USD",futures.get_active_contract("BZ"),0.0, ""),
                ("CAD","FUT","GLOBEX","USD",futures.get_active_contract("CAD"),0.0, ""),
                ("CHF","FUT","GLOBEX","USD",futures.get_active_contract("CHF"),0.0, ""),
                ("CL","FUT","NYMEX","USD",futures.get_active_contract("CL"),0.0, ""),
                ("E7","FUT","GLOBEX","USD",futures.get_active_contract("E7"),0.0, ""),
                ("EMD","FUT","GLOBEX","USD",futures.get_active_contract("EMD"),0.0, ""),
                ("ES","FUT","GLOBEX","USD",futures.get_active_contract("ES"),0.0, ""),
                ("EUR","FUT","GLOBEX","USD",futures.get_active_contract("EUR"),0.0, ""),
                ("F1U","FUT","ECBOX","USD",futures.get_active_contract("F1U"),0.0, ""),
                ("GBP","FUT","GLOBEX","USD",futures.get_active_contract("GBP"),0.0, ""),
                ("GC","FUT","NYMEX","USD",futures.get_active_contract("GC"),0.0, ""),
                ("GE","FUT","GLOBEX","USD",futures.get_active_contract("GE"),0.0, ""),
                ("GF","FUT","GLOBEX","USD",futures.get_active_contract("GF"),0.0, ""),
                ("HE","FUT","GLOBEX","USD",futures.get_active_contract("HE"),0.0, ""),
                ("HG","FUT","NYMEX","USD",futures.get_active_contract("HG"),0.0, ""),
                ("HO","FUT","NYMEX","USD",futures.get_active_contract("HO"),0.0, ""),
                ("JPY","FUT","GLOBEX","USD",futures.get_active_contract("JPY"),0.0, ""),
                ("KE","FUT","ECBOX","USD",futures.get_active_contract("KE"),0.0, ""),
                ("LE","FUT","GLOBEX","USD",futures.get_active_contract("LE"),0.0, ""),
                ("M6A","FUT","GLOBEX","USD",futures.get_active_contract("M6A"),0.0, ""),
                ("M6B","FUT","GLOBEX","USD",futures.get_active_contract("M6B"),0.0, ""),
                ("M6E","FUT","GLOBEX","USD",futures.get_active_contract("M6E"),0.0, ""),
                ("MCD","FUT","GLOBEX","USD",futures.get_active_contract("MCD"),0.0, ""),
                ("MGC","FUT","NYMEX","USD",futures.get_active_contract("MGC"),0.0, ""),
                ("MXP","FUT","GLOBEX","USD",futures.get_active_contract("MXP"),0.0, ""),
                ("N1U","FUT","ECBOX","USD",futures.get_active_contract("N1U"),0.0, ""),
                ("NG","FUT","NYMEX","USD",futures.get_active_contract("NG"),0.0, ""),
                ("NIY","FUT","GLOBEX,JPY",futures.get_active_contract("NIY"),0.0, ""),
                ("NKD","FUT","GLOBEX","USD",futures.get_active_contract("NKD"),0.0, ""),
                ("NQ","FUT","GLOBEX","USD",futures.get_active_contract("NQ"),0.0, ""),
                ("NZD","FUT","GLOBEX","USD",futures.get_active_contract("NZD"),0.0, ""),
                ("PA","FUT","NYMEX","USD",futures.get_active_contract("PA"),0.0, ""),
                ("PL","FUT","NYMEX","USD",futures.get_active_contract("PL"),0.0, ""),
                ("QM","FUT","NYMEX","USD",futures.get_active_contract("QM"),0.0, ""),
                ("RB","FUT","NYMEX","USD",futures.get_active_contract("RB"),0.0, ""),
                ("RP","FUT","GLOBEX,GBP",futures.get_active_contract("RP"),0.0, ""),
                ("SI","FUT","NYMEX","USD",futures.get_active_contract("SI"),0.0, ""),
                ("TN","FUT","ECBOX","USD",futures.get_active_contract("TN"),0.0, ""),
                ("UB","FUT","ECBOX","USD",futures.get_active_contract("UB"),0.0, ""),
                ("YM","FUT","ECBOX","USD",futures.get_active_contract("YM"),0.0, ""),
                ("ZB","FUT","ECBOX","USD",futures.get_active_contract("ZB"),0.0, ""),
                ("ZC","FUT","ECBOX","USD",futures.get_active_contract("ZC"),0.0, ""),
                ("ZF","FUT","ECBOX","USD",futures.get_active_contract("ZF"),0.0, ""),
                ("ZL","FUT","ECBOX","USD",futures.get_active_contract("ZL"),0.0, ""),
                ("ZM","FUT","ECBOX","USD",futures.get_active_contract("ZM"),0.0, ""),
                ("ZN","FUT","ECBOX","USD",futures.get_active_contract("ZN"),0.0, ""),
                ("ZS","FUT","ECBOX","USD",futures.get_active_contract("ZS"),0.0, ""),
                ("ZT","FUT","ECBOX","USD",futures.get_active_contract("ZT"),0.0, ""),
                ("ZW","FUT","ECBOX","USD",futures.get_active_contract("ZW"),0.0, ""),
            ],
        resolution  = "1D" # 1Min bar resolution (Pandas "resample" resolutions)
    )

    # run the algo
    strategy.run()

**Comment by ranaroussi** [comment]
Can you upgrade to the latest version and see if this problem was resolved?

```bash
$ pip install qtpylib --upgrade --no-cache-dir
```

Also, you can write you initialize section in the following format to achieve the same thing using a simpler codebase:

```python
if __name__ == "__main__":

    # initialize the algo
    strategy = DumbAlgo(
        instruments = [ 
            "FUT.AUD", "FUT.BZ", "FUT.CAD", "FUT.CHF", "FUT.CL", "FUT.E7", 
            "FUT.EMD", "FUT.ES", "FUT.EUR", "FUT.F1U", "FUT.GBP", "FUT.GC", 
            "FUT.GE", "FUT.GF", "FUT.HE", "FUT.HG", "FUT.HO", "FUT.JPY", 
            "FUT.KE", "FUT.LE", "FUT.M6A", "FUT.M6B", "FUT.M6E", "FUT.MCD", 
            "FUT.MGC", "FUT.MXP", "FUT.N1U", "FUT.NG", "FUT.NIY", "FUT.NKD", 
            "FUT.NQ", "FUT.NZD", "FUT.PA", "FUT.PL", "FUT.QM", "FUT.RB", "FUT.RP", 
            "FUT.SI", "FUT.TN", "FUT.UB", "FUT.YM", "FUT.ZB", "FUT.ZC", "FUT.ZF", 
            "FUT.ZL", "FUT.ZM", "FUT.ZN", "FUT.ZS", "FUT.ZT", "FUT.ZW"
        ],
        resolution  = "1D"
    )

    # run the algo
    strategy.run()
```

**Comment by ranaroussi** [comment]
Closing this for now. Please re-open if problem persist
