### ISSUE TITLE
Any chance or plans to integrate FX broker OANDA into qtpylib

### ISSUE THREAD

**Issue by developeralgo8888** [ranaroussi/qtpylib#5]
Hi Ran,  
This library is simple and great . Do you have any plans of adding or integrating FX Broker OANDA into the qtpyLib ? it would be fantastic . i love this  qtpyLib Library because it uses ZeroMQ framework in Pub/Sub architecture  . OANDA uses REST API  v1 or v2 (is the current). i think it might be easier to integrate into qtpylib.

**Comment by ranaroussi** [comment]
Hi,

I'm familiar with [oandapy](https://github.com/oanda/oandapy), and while adding support for OANDA is a great idea, I'm afraid I don't have the time to write and maintain the code at the moment as a single developer.

That being said, I will defiantly try to add this functionality once I feel QTPyLib is "done" :)
