### ISSUE TITLE
Backtesting not converting prices to float?

### ISSUE THREAD

**Issue by markmcwiggins** [ranaroussi/qtpylib#52]
I'm just trying the backtest feature; I grabbed the last 3 weeks of SPX from Google and tried to run a simple macd strategy:

   def on_bar(self, instrument):
        bars = instrument.get_bars(lookback=20)

        # make sure we have at least 20 bars to work with                                                                                                        
        if len(bars) < 20:
            return

        macd = bars.macd()

        bars['macd']        = macd['macd']
        bars['macd_signal'] = macd['signal']
        bars['macd_hist']   = macd['histogram']

        print(macd)

But I get an error:

```
python ./strategy.py --backtest --start 2016-12-20 --end 2017-01-06 --data ~/data/ --output   ~/portfolio/port.pkl
starting ...
Traceback (most recent call last):
  File "/home/ubuntu/money3/lib/python3.5/site-packages/pandas/core/ops.py", line 1170, in na_op
    raise_on_error=True, **eval_kwargs)
  File "/home/ubuntu/money3/lib/python3.5/site-packages/pandas/computation/expressions.py", line 210, in evaluate
    **eval_kwargs)
  File "/home/ubuntu/money3/lib/python3.5/site-packages/pandas/computation/expressions.py", line 63, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```
Help please ... something I'm doing wrong or an issue with the code? Thanks for a great tool!

**Comment by markmcwiggins** [comment]
More information on this: I put a debugging print statement down in the pandas code and just before the exception I get:

['SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX'
 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX'] ['SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX'
 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX' 'SPX']

So looks like it's getting the 'symbol' column rather than the 'price' column at one point in the code ...

**Comment by ranaroussi** [comment]
Sorry for the late reply...

How did you get the SPX data into the database? Did you use the `workflow` module to properly prepare / store Google's data?

http://qtpylib.io/docs/latest/workflow.html
http://qtpylib.io/docs/latest/api.html#workflow-api

LMK

**Comment by ranaroussi** [comment]
Closing for now. Please re-open if the problem resurface.
