### ISSUE TITLE
Database abstraction with SQLAlchemy

### ISSUE THREAD

**Issue by distagon** [ranaroussi/qtpylib#53]
Hi Ran,

Would you consider using SQLAlchemy as mapper and let user choose which database to use?

**Comment by ranaroussi** [comment]
YES!

**Comment by noobymcnoob** [comment]
Is this going to be relevant with your update to using PyStore? PyStore is something I'm looking forward to, databases are not the right implementation here although they work really well right now.

**Comment by ranaroussi** [comment]
MySQL will be deprecated in future updates
