### ISSUE TITLE
back testing bar data?

### ISSUE THREAD

**Issue by 4ever911** [ranaroussi/qtpylib#57]
Hi, by checking the source code, I cannot figure out how the platform handle orders while back testing. Do I have to handle it by myself?

Blotter.drip(history...)  -->   bar handler for each bar

Once a buy signal appears in the current bar, i want to create a stop order that 5 cents above the current high. How do I know if the order is filled through the platform? Do I have to implement by myself,i.e fill/cancel/modify order status during next bar?  And how can i get the back testing results?

**Comment by ricpruss** [comment]
You have to run a second program against the blotter.  It is called a strategy and you can see the on_bar example in the examples directory in an example stratergy there.  There is some good doc and an example of this here: http://qtpylib.io/docs/latest/algo.html
