### ISSUE TITLE
disable continuous contract

### ISSUE THREAD

**Issue by JfourierX** [ranaroussi/qtpylib#6]
Is there anyway to turn off the automatic continuous contract selection in the preload ? I am trying to preload CLZ2016, but it is loading CLX2016.

**Comment by ranaroussi** [comment]
Hi JfourierX,

At the moment QTPyLib defaults to a continuous contract when pulling historical data and the only way to get around that is to request data from when the earlier contract has already expired.

I admit this is a use case I haven't thought about and will add a flag to skip the continuous contract construction in the next release of QTPyLib.

Ran

**Comment by ranaroussi** [comment]
This functionality was just added to version 1.4.9.

Simply add `continuous = False` to your strategy initializer.

```
strategy = MyStrategy(
        instruments = [ ("CL", "FUT", "NYMEX", "USD", 201611) ],
        preload = 5D,
        continuous = False,
       ...
    )
```

**Comment by ranaroussi** [comment]
Marking this issue as closed for now
