### ISSUE TITLE
Twilio Client Error

### ISSUE THREAD

**Issue by twopirllc** [ranaroussi/qtpylib#65]
Hello Ran,

Running Twilio 6.0.0 module.  Had to change the following 'import' to get a simple Algo to execute.
Also as a Feature Request, perhaps enabling or disabling sms as an option?  Since some may not use Twilio or Nextmo for alerts and messages.  In no rush, still learning the API ecosystem.

File: sms.py
`# from twilio.rest import TwilioRestClient as twilioClient`
`from twilio.rest import Client as twilioClient`

Keep up the good work.
Thanks
KJ

**Comment by ranaroussi** [comment]
Fixed in latest release (v 1.5.72).

Please upgrade using:

```bash
$ pip install qtpylib --upgrade --no-cache-dir
```
