### ISSUE TITLE
Not submitting orders

### ISSUE THREAD

**Issue by riskysp** [ranaroussi/qtpylib#66]
I have the newest version and have installed a number of times. Blotter running fine, but DumbAlgo continues to report the following:

2017-05-18 16:50:01,147 [WARNING] qtpylib.broker: Not submitting AAPL order, orders pending: {'AAPL': {'quantity': 100, 'expires': datetime.datetime(2017, 5, 18, 16, 50, 1, 582007), 'orderId': 1}}

Any diagnostics I can run to figure this out?

**Comment by nikeshpatel22** [comment]
Also having this same problem? Any updates?

Thanks in advance!

**Comment by nikeshpatel22** [comment]
This is the error message I receive

[WARNING] qtpylib.broker: Not submitting AAPL order, orders pending: {'AAPL': {'orderId': 1, 'quantity': 100, 'expires': datetime.datetime(2017, 7, 21, 11, 51, 2, 435810)}}

**Comment by ranaroussi** [comment]
Please upgrade to ``ezIBpy 1.12.55`` and let me know if the problem got fixed.

Upgrade using:
```bash
$ pip install ezibpy --upgrade
```

**Comment by nikeshpatel22** [comment]
Still encountering same problem

**Comment by ranaroussi** [comment]
Are you using the latest version of QTPyLib? I’m not able to reproduce this error. Works fine on both my dev and live trading machine...

**Comment by acennami** [comment]
I am having the same issue on a new installation today.  Was a separate resolution found?  I'm on 1.12.56 ezibpy and 1.5.76 qtpylib.
