### ISSUE TITLE
datetime.strftime('%s') is not supported in Windows platform

### ISSUE THREAD

**Issue by ryanaaa** [ranaroussi/qtpylib#69]
in file qtpylib/reports.py. it use datetime.strftime('%s'). this format seems only supported in unix system. it will raise an Error in Windows platform. [see the answer of Ulf Aslak in stackoverflow](https://stackoverflow.com/questions/8777753/converting-datetime-date-to-utc-timestamp-in-python)

In python's official doc: https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior . the format '%s' is not mentioned also.

**Comment by ranaroussi** [comment]
Fixed. Forgot to close this issue
