### ISSUE TITLE
Index instruments

### ISSUE THREAD

**Issue by mariope** [ranaroussi/qtpylib#72]
I'm trying to retrieve data for the instrument TRIN-NYSE from IB.

instruments = [ ("TRIN-NYSE", "IND", "NYSE", "USD") ]

I've tried to retrieve other indices too, like 
VIX,IND,CBOE,USD,,0.0,
CIPCR,IND,CBOE,USD,,0.0,

but doesn't work, blotter say that "Contract added", the instrument appears in symbols.csv, but never into the DB.

For Futures and Stocks works fine.

I've tested to download the same data from IB with R (IBrokers) and works fine. I mean, I have available these instrument from TWS API.

I appreciate any help.

**Comment by ranaroussi** [comment]
You should add these as IB tuples. 
See here: http://qtpylib.io/docs/latest/algo.html#instruments-tuples
