### ISSUE TITLE
apply indicator on each other 

### ISSUE THREAD

**Issue by macd2** [ranaroussi/qtpylib#76]
Hello,
how can i apply one indicator onto another indicator? 
For example RSI on EMA10

**Comment by ranaroussi** [comment]
Sure! This should look something like:

```python
bars = instrument.get_bars(window=100)
bars['rsi'] = bars['close'].rsi(window=14)
bars['rsi_ema10'] = bars['rsi'].rolling_weighted_mean(10)
```

or simpy:

```python
bars = instrument.get_bars(window=100)
bars['rsi_ema10'] = bars['close'].rsi(window=14).rolling_weighted_mean(10)
```

**Comment by macd2** [comment]
brilliant thanks 👍 
May i ask one more question how can i apply an indicator to a defined amount of candles (close values)? 
Like 
`dataframe['Close5']= qtpylib.CLOSE_VALUE_OF_THE_LAST_5_CANDLES`

**Comment by ranaroussi** [comment]
The values for the indicators are returned for the entire data you pass to it, so:

```python
bars = instrument.get_bars()
bars['ema10'] = bars['close'].rolling_mean(10)
```

In this case, ``bars['ema10']`` will have data for the entire ``bars['close']`` data, starting from the 11th bar.
