### ISSUE TITLE
It seems ezIBpy cannot work with the newest version of TWS...

### ISSUE THREAD

**Issue by wangzhe3224** [ranaroussi/qtpylib#78]
The code stucked at the connect() function. No response.

**Comment by ranaroussi** [comment]
Just tested it on TWS Build 970.0n (Feb 2018) and everything's fine. 

Have you configured TWS properly to allow API connections? Are you using the correct port number?

Please see this guide:
http://qtpylib.io/docs/latest/install.html#configure-for-api-access

I'm closing this issue. If the problem persists, please open a new issue on [ezIBpy](https://github.com/ranaroussi/ezibpy)'s repository.
