### ISSUE TITLE
secType OPT, FOP order

### ISSUE THREAD

**Issue by gitsamsit** [ranaroussi/qtpylib#8]
Hi Ran

I am trying to test placing order for secType OPT and FOP (using version 4.91). Looks like tick data is coming through but nothing into db tables.

Is this working at your side.

Test Tuple:
("ES", "FOP", "GLOBEX", "USD", 20161216, 2120, "PUT")
("AAPL", "OPT", "SMART", "USD", 20161028, 115.0, "PUT")

Not sure anything obvious that I am missing.  Could you please check this out.

Thanks!

**Comment by ranaroussi** [comment]
Options should be fully supported within a few days

**Comment by ranaroussi** [comment]
Version 1.4.92a includes full support for Options trading. Enjoy :)
