### ISSUE TITLE
backtest performance

### ISSUE THREAD

**Issue by andreireiand** [ranaroussi/qtpylib#89]
Do you have any stats around backtest performance ... vectorized or otherwise ...for example a dual mov. avg. w/ 1000 values on the short MA and 1000 values on the long MA - how would such an optimization run? thx

**Comment by ranaroussi** [comment]
Vectorized backtesters will always be faster than event-based ones (like QTPyLib). That being said, they also have their flaws, especially relating to look-ahead bias.

I would suggest using a vectorized backtester for optimizing 1000*1000 parameters, identify the areas where you get better results and then test a much smaller set using an event-based backtester.

Basically: idea->prototype->backtest
