### ISSUE TITLE
Dashboard display

### ISSUE THREAD

**Issue by schalkw-gmail-com** [ranaroussi/qtpylib#92]
I'm trying to run the dashboard but all the files that need including, requires to be in a static folder and there is no static folder in the code. Even if you add a static folder with the files inside they do not load.

Any idea ?

**Comment by ranaroussi** [comment]
The static folder is ``/_webapp`` which is included in the distribution. Make sure you have your blotter running before running the dashboard module.

**Comment by lionelyoung** [comment]
I'm having the same issue, getting this error:
`TypeError: send_static() got an unexpected keyword argument 'path'`

I checked that the Blotter is running, and I put a copy of _webapp into the same location as dashboard, and I run it as `python mydashboard.py --nopass`

Here is my dashboard code:
```
from qtpylib.reports import Reports

class Dashboard(Reports):
    pass # we just need the name

if __name__ == "__main__":
    dashboard = Dashboard(port = 5000)
    dashboard.run()

```

**Comment by lionelyoung** [comment]
#99 should close this, just tested it and it resolves the issue
