### ISSUE TITLE
Tick Data

### ISSUE THREAD

**Issue by schalkw-gmail-com** [ranaroussi/qtpylib#95]
This might be the incorrect place, but some help will be really appreciated.

I'm struggling to find the documentation / explanation of how the frequencies work. When is something a bar and when is it a tick?

What I want to do is have bars that is made up of 2000 ticks (eg. 1 tick = 1 trade thus 2000 trades).

Is this possible?

**Comment by lionelyoung** [comment]
Hi @schalkw-gmail-com,

If you send in the "resolution" parameter as "2000K" it will use tick bars

For example, this will be 1H bars
```
strategy = MyStrategy(
    instruments = [ "AAPL" ],
    resolution  = "1H", # 1 hour bars
)
```

For example, this will be 2000 tick bars
```
strategy = MyStrategy(
    instruments = [ "AAPL" ],
    resolution  = "2000K", # 2000 tick bars
)
```

Here is a link to the relevant location in the documentation: [link](https://qtpylib.io/docs/latest/algo.html#algo-parameters)
